### ISSUE TITLE
T7 caveman-economy: 75 pre-existing entities.description function-word-ratio FAILs block T7/T10 -- debt vs. ceiling-tuning undetermined

### ISSUE THREAD

**Issue by djwmobley** [djwmobley/claude-memory#212]
## Summary

`verify-15-t7-caveman-economy.js`'s store-wide gate (`test/north-star/test-caveman-economy-store-wide.js`) FAILs against `memory_manager_staging` on **75 `entities.description` rows** for function-word-ratio economy violations. These predate PR #211 and are unrelated to it — that PR only fixed the K-8 completeness classification for the two migrate-07 lineage tables. Observed 2026-08-19, reproduced first-hand during PR #211's independent review.

## First-hand observation (2026-08-19, PR #211 head b190ef5, target `memory_manager_staging`)

```
completeness (K-8): PASS
rows scanned: 3183 across 32 table(s)
  entities: scanned=473 FAILED=75
...
RESULT: FAIL
[T7] FAIL: store-wide gate reported failure.
```

- Exactly 75 economy FAILs; **all 75** on `entities.description` (class=`checked-caveman`); zero on any other table/column.
- 75 of 473 scanned `entities` rows (~15.9%).
- Function-word ratios span **30.8%–57.1%** against the 30% caveman ceiling; entity ids span #639–#943.
- Every FAIL line carries the K-5 caveat: "no synthetic-baseline comparison, density-ceiling only".

## Why this needs investigation (root cause undetermined)

Two competing explanations, not yet distinguished:

1. **Real caveman-economy debt** — migrated entity descriptions genuinely authored in non-telegraphic prose that should be rewritten/condensed.
2. **Ceiling/heuristic tuning issue** — the 30% function-word ceiling may be miscalibrated for the `entities.description` column class (short noun-phrase-ish descriptions where a single "of"/"for" in a 5-10-word string blows past 30% arithmetically without indicating verbose prose; many observed ratios are 33.3%/40%/50% — i.e., small-denominator artifacts).

Deciding between these requires reading a sample of the 75 rows and/or comparing against the K-5 synthetic-baseline approach the current check explicitly does not implement.

## Impact

- Blocks T7 (`verify-15-t7-caveman-economy.js` exits FAIL) and therefore the full-battery T10 gate, **independently of all other open work** — now the only remaining T7 failure class after PR #211 fixed K-8 completeness.

## Context

- Surfaced by the author of PR #211 (see its Test plan / Blind Spots) and reproduced independently during that PR's review (see the review comment on #211).
- Note from the review: pre-#211, these 75 were **masked** — the K-8 completeness FAIL short-circuited the gate with 0 rows scanned. #211 unmasked them; it did not introduce them (its diff touches no data and no entities rows).

## Blind spots — what this observation canNOT establish

- Whether the 75 descriptions are actually bad memory-economy prose vs. arithmetically-doomed short strings — nobody has read the row contents yet; the count and ratios alone cannot distinguish debt from miscalibration.
- Whether the population is stable — 473 live entities rows were scanned on 2026-08-19; ongoing sessions add/suppress entities, so the 75 figure is a point-in-time snapshot, not a fixed backlog.
- Whether the same violation pattern exists in other stores/DBs — only `memory_manager_staging` was checked.
- Whether the 30% ceiling is wrong in general or only for this column class — the density-ceiling-only check (K-5 caveat) has no synthetic-baseline comparison to calibrate against.
